# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


france_1399 = Map.create(title:"France in 1399", year: 1399, url:"mapbox://styles/sean-para/cjoyxpl7l1r6x2rmhh5xa7gsf")

france_1399_description = MapDescription.create(map_id: 1, title: "France in 1399", text: "1399 was a time of French triumph. England had seen three decades of defeat and the collapse of English rule in Aquitaine as well as their loss of influence in Brittany. The French monarchy had regained its self-confidence after approaching the brink of collapse during the late 1350s and early 1360s. Flanders was brought definitively into the French sphere of influence following Phillip the Bold’s marriage to Margaret of Flanders and the defeat of Ghent and its allied towns at the Battle of Roosebeke in 1382. In 1396, a twenty-eight-year truce was agreed upon. The truce aimed to resolve the conflict by exchanging territorial concessions in southwestern France for an acknowledgement of French sovereignty over England’s continental dominions. However, Richard II was deposed by his cousin Henry of Bolingbroke after his attempt to disinherit the House of Lancaster following John of Gaunt’s death. Henry IV’s accession ultimately resulted in renewed conflict, as the French monarchy sought to unseat him by supporting a number of rebellions against the English crown, poisoning the fragile peace between the two countries, and leading the way for Henry V’s invasion of France to buttress his young dynasty’s legitimacy." )

france_1429 = Map.create(title:"France in 1429", year: 1429, url:"mapbox://styles/sean-para/cjooeq11s245t2spc490zj65f")

france_1429_description = MapDescription.create(map_id: 2, title: "France in 1429", text: "France in 1429 was riven by two decades of civil war and foreign occupation. The assassination of Louis, Duke of Orléans – a prince of the blood and de facto regent for his insane brother Charles VI – by henchman of John the Fearless, Duke of Burgundy, unleashed a brutal civil war between the Armagnacs – supported of the House of Orleans – and the Burgundians. The conflict eventually drew in the English, and Henry V was able to take advantage of the extreme factionalism and exploit the governmental vacuum to conquer much of northern France. The assassination of John the Fearless in 1419 drove his son, Philip the Good, into an alliance with Henry V against the Armagnac faction, now titularly led by the Dauphin, son of Charles VI and future king of France. The next nine years saw further English successes, first under Henry V and then after his death in 1422, under the Duke of Bedford as regent for his young nephew, Henry VI. Nonetheless, they remained unable to penetrate beyond the Loire. In 1429, Orleans – a principal Valois stronghold and the key the regions south of the Loire – was under siege and seemed close to falling. It would ultimately be saved by a relief army that was brought to life by Joan of Arc. The relief of Orleans was followed by the first major English defeat in eight years at the Battle of Patay, followed by the collapse of the Lancastrian position in Champagne and the coronation of Charles VII at Rheims. Thus, 1429 proved to be the high-water mark of England’s attempt to conquer France, with the next two decades seeing the retreat of England’s frontiers and their ultimate expulsion from France in 1453.")

# agincourt = HistoricalEvent.create(title: "Agincourt", description: "Henry V kicked some ass", latitude: 50.4630, longitude: 2.1285, map_id: 2)
# agincourt.image.attach(io: File.open("./images/Roman-Empire_565ad_sm.jpeg"), filename: "Roman-Empire_565ad_sm.jpeg", content_type: 'jpeg')
